#!/usr/bin/env node

var exec = require('child_process').exec;

function outputTestError(stderr) {
  var errs = stderr.split('\n');
  var indexOfMessage = -1;
  for (var i = 0; i < errs.length ; i++) {
    if (errs[i].indexOf('The message provided') > -1) {
      indexOfMessage = i;
      break;
    }
  }
  if ( indexOfMessage === -1) {
    // syntax err
    errs.forEach(function(e) {
      console.error(e);
    });
  } else {
    // test failure
    errs.slice(indexOfMessage).forEach(function(error) {
      if (error.match(/^\s+at.+/)) return;
      if (error.match(/^\s+\d/)) {
        error = error.trim();
      }
      console.error(error);
    });
  }
}

function outputTestSuccess(stdout) {
  var lines = stdout.split('\n').filter(function(line) {
    if (line === ': ""') return false;
    if (line.trim() === '') return false;
    return true;
  }).forEach(function(l) {
    console.log(l);
  });
}

exec('./scripts/elm-test', function(err, stdout, stderr) {
  !!stderr ? outputTestError(stderr) : outputTestSuccess(stdout);

  process.exit(err && err.code || 0);
});
